// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.1
// source: satelitDatastore.proto

package satelit_datastore

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DHCPLease struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MacAddress     string `protobuf:"bytes,1,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	Ip             string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Network        string `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	Gateway        string `protobuf:"bytes,4,opt,name=gateway,proto3" json:"gateway,omitempty"`
	DnsServer      string `protobuf:"bytes,5,opt,name=dns_server,json=dnsServer,proto3" json:"dns_server,omitempty"`
	MetadataServer string `protobuf:"bytes,6,opt,name=metadata_server,json=metadataServer,proto3" json:"metadata_server,omitempty"`
}

func (x *DHCPLease) Reset() {
	*x = DHCPLease{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satelitDatastore_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DHCPLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DHCPLease) ProtoMessage() {}

func (x *DHCPLease) ProtoReflect() protoreflect.Message {
	mi := &file_satelitDatastore_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DHCPLease.ProtoReflect.Descriptor instead.
func (*DHCPLease) Descriptor() ([]byte, []int) {
	return file_satelitDatastore_proto_rawDescGZIP(), []int{0}
}

func (x *DHCPLease) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *DHCPLease) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *DHCPLease) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *DHCPLease) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *DHCPLease) GetDnsServer() string {
	if x != nil {
		return x.DnsServer
	}
	return ""
}

func (x *DHCPLease) GetMetadataServer() string {
	if x != nil {
		return x.MetadataServer
	}
	return ""
}

type GetDHCPLeaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MacAddress string `protobuf:"bytes,1,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
}

func (x *GetDHCPLeaseRequest) Reset() {
	*x = GetDHCPLeaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satelitDatastore_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDHCPLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDHCPLeaseRequest) ProtoMessage() {}

func (x *GetDHCPLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_satelitDatastore_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDHCPLeaseRequest.ProtoReflect.Descriptor instead.
func (*GetDHCPLeaseRequest) Descriptor() ([]byte, []int) {
	return file_satelitDatastore_proto_rawDescGZIP(), []int{1}
}

func (x *GetDHCPLeaseRequest) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

type GetDHCPLeaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lease *DHCPLease `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
}

func (x *GetDHCPLeaseResponse) Reset() {
	*x = GetDHCPLeaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satelitDatastore_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDHCPLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDHCPLeaseResponse) ProtoMessage() {}

func (x *GetDHCPLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_satelitDatastore_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDHCPLeaseResponse.ProtoReflect.Descriptor instead.
func (*GetDHCPLeaseResponse) Descriptor() ([]byte, []int) {
	return file_satelitDatastore_proto_rawDescGZIP(), []int{2}
}

func (x *GetDHCPLeaseResponse) GetLease() *DHCPLease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type GetHostnameByAddressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *GetHostnameByAddressRequest) Reset() {
	*x = GetHostnameByAddressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satelitDatastore_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHostnameByAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostnameByAddressRequest) ProtoMessage() {}

func (x *GetHostnameByAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_satelitDatastore_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostnameByAddressRequest.ProtoReflect.Descriptor instead.
func (*GetHostnameByAddressRequest) Descriptor() ([]byte, []int) {
	return file_satelitDatastore_proto_rawDescGZIP(), []int{3}
}

func (x *GetHostnameByAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetHostnameByAddressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
}

func (x *GetHostnameByAddressResponse) Reset() {
	*x = GetHostnameByAddressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satelitDatastore_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHostnameByAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostnameByAddressResponse) ProtoMessage() {}

func (x *GetHostnameByAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_satelitDatastore_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostnameByAddressResponse.ProtoReflect.Descriptor instead.
func (*GetHostnameByAddressResponse) Descriptor() ([]byte, []int) {
	return file_satelitDatastore_proto_rawDescGZIP(), []int{4}
}

func (x *GetHostnameByAddressResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type ListBridgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListBridgeRequest) Reset() {
	*x = ListBridgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satelitDatastore_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBridgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBridgeRequest) ProtoMessage() {}

func (x *ListBridgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_satelitDatastore_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBridgeRequest.ProtoReflect.Descriptor instead.
func (*ListBridgeRequest) Descriptor() ([]byte, []int) {
	return file_satelitDatastore_proto_rawDescGZIP(), []int{5}
}

type ListBridgeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bridges []*ListBridgeResponse_Bridge `protobuf:"bytes,1,rep,name=bridges,proto3" json:"bridges,omitempty"`
}

func (x *ListBridgeResponse) Reset() {
	*x = ListBridgeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satelitDatastore_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBridgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBridgeResponse) ProtoMessage() {}

func (x *ListBridgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_satelitDatastore_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBridgeResponse.ProtoReflect.Descriptor instead.
func (*ListBridgeResponse) Descriptor() ([]byte, []int) {
	return file_satelitDatastore_proto_rawDescGZIP(), []int{6}
}

func (x *ListBridgeResponse) GetBridges() []*ListBridgeResponse_Bridge {
	if x != nil {
		return x.Bridges
	}
	return nil
}

type CorePair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhysicalCore uint32  `protobuf:"varint,1,opt,name=physical_core,json=physicalCore,proto3" json:"physical_core,omitempty"`
	LogicalCore  *uint32 `protobuf:"varint,2,opt,name=logical_core,json=logicalCore,proto3,oneof" json:"logical_core,omitempty"`
}

func (x *CorePair) Reset() {
	*x = CorePair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satelitDatastore_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CorePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorePair) ProtoMessage() {}

func (x *CorePair) ProtoReflect() protoreflect.Message {
	mi := &file_satelitDatastore_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorePair.ProtoReflect.Descriptor instead.
func (*CorePair) Descriptor() ([]byte, []int) {
	return file_satelitDatastore_proto_rawDescGZIP(), []int{7}
}

func (x *CorePair) GetPhysicalCore() uint32 {
	if x != nil {
		return x.PhysicalCore
	}
	return 0
}

func (x *CorePair) GetLogicalCore() uint32 {
	if x != nil && x.LogicalCore != nil {
		return *x.LogicalCore
	}
	return 0
}

type NumaNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pairs           []*CorePair `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	PhysicalCoreMin uint32      `protobuf:"varint,2,opt,name=physical_core_min,json=physicalCoreMin,proto3" json:"physical_core_min,omitempty"`
	PhysicalCoreMax uint32      `protobuf:"varint,3,opt,name=physical_core_max,json=physicalCoreMax,proto3" json:"physical_core_max,omitempty"`
	LogicalCoreMin  *uint32     `protobuf:"varint,4,opt,name=logical_core_min,json=logicalCoreMin,proto3,oneof" json:"logical_core_min,omitempty"`
	LogicalCoreMax  *uint32     `protobuf:"varint,5,opt,name=logical_core_max,json=logicalCoreMax,proto3,oneof" json:"logical_core_max,omitempty"`
}

func (x *NumaNode) Reset() {
	*x = NumaNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satelitDatastore_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumaNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumaNode) ProtoMessage() {}

func (x *NumaNode) ProtoReflect() protoreflect.Message {
	mi := &file_satelitDatastore_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumaNode.ProtoReflect.Descriptor instead.
func (*NumaNode) Descriptor() ([]byte, []int) {
	return file_satelitDatastore_proto_rawDescGZIP(), []int{8}
}

func (x *NumaNode) GetPairs() []*CorePair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

func (x *NumaNode) GetPhysicalCoreMin() uint32 {
	if x != nil {
		return x.PhysicalCoreMin
	}
	return 0
}

func (x *NumaNode) GetPhysicalCoreMax() uint32 {
	if x != nil {
		return x.PhysicalCoreMax
	}
	return 0
}

func (x *NumaNode) GetLogicalCoreMin() uint32 {
	if x != nil && x.LogicalCoreMin != nil {
		return *x.LogicalCoreMin
	}
	return 0
}

func (x *NumaNode) GetLogicalCoreMax() uint32 {
	if x != nil && x.LogicalCoreMax != nil {
		return *x.LogicalCoreMax
	}
	return 0
}

type RegisterTeleskopAgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string      `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Endpoint string      `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Iqn      string      `protobuf:"bytes,4,opt,name=iqn,proto3" json:"iqn,omitempty"`
	Nodes    []*NumaNode `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *RegisterTeleskopAgentRequest) Reset() {
	*x = RegisterTeleskopAgentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satelitDatastore_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterTeleskopAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTeleskopAgentRequest) ProtoMessage() {}

func (x *RegisterTeleskopAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_satelitDatastore_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTeleskopAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterTeleskopAgentRequest) Descriptor() ([]byte, []int) {
	return file_satelitDatastore_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterTeleskopAgentRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterTeleskopAgentRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisterTeleskopAgentRequest) GetIqn() string {
	if x != nil {
		return x.Iqn
	}
	return ""
}

func (x *RegisterTeleskopAgentRequest) GetNodes() []*NumaNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type RegisterTeleskopAgentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterTeleskopAgentResponse) Reset() {
	*x = RegisterTeleskopAgentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satelitDatastore_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterTeleskopAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTeleskopAgentResponse) ProtoMessage() {}

func (x *RegisterTeleskopAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_satelitDatastore_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTeleskopAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterTeleskopAgentResponse) Descriptor() ([]byte, []int) {
	return file_satelitDatastore_proto_rawDescGZIP(), []int{10}
}

type GetCPUCoreByPinningGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname         string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	PinningGroupName string `protobuf:"bytes,2,opt,name=pinning_group_name,json=pinningGroupName,proto3" json:"pinning_group_name,omitempty"`
}

func (x *GetCPUCoreByPinningGroupRequest) Reset() {
	*x = GetCPUCoreByPinningGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satelitDatastore_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCPUCoreByPinningGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCPUCoreByPinningGroupRequest) ProtoMessage() {}

func (x *GetCPUCoreByPinningGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_satelitDatastore_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCPUCoreByPinningGroupRequest.ProtoReflect.Descriptor instead.
func (*GetCPUCoreByPinningGroupRequest) Descriptor() ([]byte, []int) {
	return file_satelitDatastore_proto_rawDescGZIP(), []int{11}
}

func (x *GetCPUCoreByPinningGroupRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetCPUCoreByPinningGroupRequest) GetPinningGroupName() string {
	if x != nil {
		return x.PinningGroupName
	}
	return ""
}

type GetCPUCoreByPinningGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pairs []*CorePair `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
}

func (x *GetCPUCoreByPinningGroupResponse) Reset() {
	*x = GetCPUCoreByPinningGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satelitDatastore_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCPUCoreByPinningGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCPUCoreByPinningGroupResponse) ProtoMessage() {}

func (x *GetCPUCoreByPinningGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_satelitDatastore_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCPUCoreByPinningGroupResponse.ProtoReflect.Descriptor instead.
func (*GetCPUCoreByPinningGroupResponse) Descriptor() ([]byte, []int) {
	return file_satelitDatastore_proto_rawDescGZIP(), []int{12}
}

func (x *GetCPUCoreByPinningGroupResponse) GetPairs() []*CorePair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type ListBridgeResponse_Bridge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name            string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VlanId          uint32 `protobuf:"varint,2,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	ParentInterface string `protobuf:"bytes,3,opt,name=parent_interface,json=parentInterface,proto3" json:"parent_interface,omitempty"`
	MetadataCidr    string `protobuf:"bytes,4,opt,name=metadata_cidr,json=metadataCidr,proto3" json:"metadata_cidr,omitempty"`
	InternalOnly    bool   `protobuf:"varint,5,opt,name=internal_only,json=internalOnly,proto3" json:"internal_only,omitempty"`
}

func (x *ListBridgeResponse_Bridge) Reset() {
	*x = ListBridgeResponse_Bridge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satelitDatastore_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBridgeResponse_Bridge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBridgeResponse_Bridge) ProtoMessage() {}

func (x *ListBridgeResponse_Bridge) ProtoReflect() protoreflect.Message {
	mi := &file_satelitDatastore_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBridgeResponse_Bridge.ProtoReflect.Descriptor instead.
func (*ListBridgeResponse_Bridge) Descriptor() ([]byte, []int) {
	return file_satelitDatastore_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ListBridgeResponse_Bridge) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListBridgeResponse_Bridge) GetVlanId() uint32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

func (x *ListBridgeResponse_Bridge) GetParentInterface() string {
	if x != nil {
		return x.ParentInterface
	}
	return ""
}

func (x *ListBridgeResponse_Bridge) GetMetadataCidr() string {
	if x != nil {
		return x.MetadataCidr
	}
	return ""
}

func (x *ListBridgeResponse_Bridge) GetInternalOnly() bool {
	if x != nil {
		return x.InternalOnly
	}
	return false
}

var File_satelitDatastore_proto protoreflect.FileDescriptor

var file_satelitDatastore_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x74, 0x44, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x73, 0x61, 0x74, 0x65, 0x6c, 0x69,
	0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x22, 0xb8, 0x01, 0x0a, 0x09,
	0x44, 0x48, 0x43, 0x50, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x63,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x1d,
	0x0a, 0x0a, 0x64, 0x6e, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x64, 0x6e, 0x73, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x27, 0x0a,
	0x0f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x36, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x44, 0x48, 0x43,
	0x50, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x6d, 0x61, 0x63, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x4a,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x44, 0x48, 0x43, 0x50, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x74, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x44, 0x48, 0x43, 0x50, 0x4c, 0x65,
	0x61, 0x73, 0x65, 0x52, 0x05, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x22, 0x37, 0x0a, 0x1b, 0x47, 0x65,
	0x74, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x22, 0x3a, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61,
	0x6d, 0x65, 0x42, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x89, 0x02, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x07, 0x62,
	0x72, 0x69, 0x64, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x73,
	0x61, 0x74, 0x65, 0x6c, 0x69, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x52, 0x07, 0x62, 0x72, 0x69, 0x64,
	0x67, 0x65, 0x73, 0x1a, 0xaa, 0x01, 0x0a, 0x06, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x76, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x76, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x63, 0x69, 0x64, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x43, 0x69, 0x64, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4f, 0x6e, 0x6c, 0x79,
	0x22, 0x68, 0x0a, 0x08, 0x43, 0x6f, 0x72, 0x65, 0x50, 0x61, 0x69, 0x72, 0x12, 0x23, 0x0a, 0x0d,
	0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0c, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x43, 0x6f, 0x72,
	0x65, 0x12, 0x26, 0x0a, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x72,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x63,
	0x61, 0x6c, 0x43, 0x6f, 0x72, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x6c, 0x6f,
	0x67, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x9d, 0x02, 0x0a, 0x08, 0x4e,
	0x75, 0x6d, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x74,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x43, 0x6f, 0x72, 0x65, 0x50,
	0x61, 0x69, 0x72, 0x52, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x68,
	0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x6d, 0x69, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x43,
	0x6f, 0x72, 0x65, 0x4d, 0x69, 0x6e, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63,
	0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0f, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x43, 0x6f, 0x72, 0x65, 0x4d,
	0x61, 0x78, 0x12, 0x2d, 0x0a, 0x10, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x63, 0x6f,
	0x72, 0x65, 0x5f, 0x6d, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x0e,
	0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x43, 0x6f, 0x72, 0x65, 0x4d, 0x69, 0x6e, 0x88, 0x01,
	0x01, 0x12, 0x2d, 0x0a, 0x10, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x72,
	0x65, 0x5f, 0x6d, 0x61, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x01, 0x52, 0x0e, 0x6c,
	0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x43, 0x6f, 0x72, 0x65, 0x4d, 0x61, 0x78, 0x88, 0x01, 0x01,
	0x42, 0x13, 0x0a, 0x11, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x72,
	0x65, 0x5f, 0x6d, 0x69, 0x6e, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61,
	0x6c, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x6d, 0x61, 0x78, 0x22, 0x9b, 0x01, 0x0a, 0x1c, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x65, 0x6c, 0x65, 0x73, 0x6b, 0x6f, 0x70, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x68,
	0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68,
	0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x71, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x69, 0x71, 0x6e, 0x12, 0x31, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x74, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x4e, 0x75, 0x6d, 0x61, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x1f, 0x0a, 0x1d, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x54, 0x65, 0x6c, 0x65, 0x73, 0x6b, 0x6f, 0x70, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6b, 0x0a, 0x1f, 0x47, 0x65, 0x74,
	0x43, 0x50, 0x55, 0x43, 0x6f, 0x72, 0x65, 0x42, 0x79, 0x50, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x70, 0x69, 0x6e, 0x6e,
	0x69, 0x6e, 0x67, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x55, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x43, 0x50, 0x55,
	0x43, 0x6f, 0x72, 0x65, 0x42, 0x79, 0x50, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x70, 0x61,
	0x69, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x61, 0x74, 0x65,
	0x6c, 0x69, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x43, 0x6f,
	0x72, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x32, 0xd3, 0x04,
	0x0a, 0x10, 0x53, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x74, 0x44, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x12, 0x61, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x44, 0x48, 0x43, 0x50, 0x4c, 0x65, 0x61,
	0x73, 0x65, 0x12, 0x26, 0x2e, 0x73, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x74, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x48, 0x43, 0x50, 0x4c, 0x65,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x73, 0x61, 0x74,
	0x65, 0x6c, 0x69, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x44, 0x48, 0x43, 0x50, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x79, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x42, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2e, 0x2e,
	0x73, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x79, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e,
	0x73, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x79, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x5b, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x12, 0x24,
	0x2e, 0x73, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x73, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x74, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x7c, 0x0a,
	0x15, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x65, 0x6c, 0x65, 0x73, 0x6b, 0x6f,
	0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x2f, 0x2e, 0x73, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x74,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x54, 0x65, 0x6c, 0x65, 0x73, 0x6b, 0x6f, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x73, 0x61, 0x74, 0x65, 0x6c, 0x69,
	0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x54, 0x65, 0x6c, 0x65, 0x73, 0x6b, 0x6f, 0x70, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x85, 0x01, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x43, 0x50, 0x55, 0x43, 0x6f, 0x72, 0x65, 0x42, 0x79, 0x50, 0x69, 0x6e, 0x6e,
	0x69, 0x6e, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x32, 0x2e, 0x73, 0x61, 0x74, 0x65, 0x6c,
	0x69, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x43, 0x50, 0x55, 0x43, 0x6f, 0x72, 0x65, 0x42, 0x79, 0x50, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x73,
	0x61, 0x74, 0x65, 0x6c, 0x69, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x50, 0x55, 0x43, 0x6f, 0x72, 0x65, 0x42, 0x79, 0x50, 0x69, 0x6e,
	0x6e, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x3b, 0x73, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x74,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_satelitDatastore_proto_rawDescOnce sync.Once
	file_satelitDatastore_proto_rawDescData = file_satelitDatastore_proto_rawDesc
)

func file_satelitDatastore_proto_rawDescGZIP() []byte {
	file_satelitDatastore_proto_rawDescOnce.Do(func() {
		file_satelitDatastore_proto_rawDescData = protoimpl.X.CompressGZIP(file_satelitDatastore_proto_rawDescData)
	})
	return file_satelitDatastore_proto_rawDescData
}

var file_satelitDatastore_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_satelitDatastore_proto_goTypes = []interface{}{
	(*DHCPLease)(nil),                        // 0: satelit_datastore.DHCPLease
	(*GetDHCPLeaseRequest)(nil),              // 1: satelit_datastore.GetDHCPLeaseRequest
	(*GetDHCPLeaseResponse)(nil),             // 2: satelit_datastore.GetDHCPLeaseResponse
	(*GetHostnameByAddressRequest)(nil),      // 3: satelit_datastore.GetHostnameByAddressRequest
	(*GetHostnameByAddressResponse)(nil),     // 4: satelit_datastore.GetHostnameByAddressResponse
	(*ListBridgeRequest)(nil),                // 5: satelit_datastore.ListBridgeRequest
	(*ListBridgeResponse)(nil),               // 6: satelit_datastore.ListBridgeResponse
	(*CorePair)(nil),                         // 7: satelit_datastore.CorePair
	(*NumaNode)(nil),                         // 8: satelit_datastore.NumaNode
	(*RegisterTeleskopAgentRequest)(nil),     // 9: satelit_datastore.RegisterTeleskopAgentRequest
	(*RegisterTeleskopAgentResponse)(nil),    // 10: satelit_datastore.RegisterTeleskopAgentResponse
	(*GetCPUCoreByPinningGroupRequest)(nil),  // 11: satelit_datastore.GetCPUCoreByPinningGroupRequest
	(*GetCPUCoreByPinningGroupResponse)(nil), // 12: satelit_datastore.GetCPUCoreByPinningGroupResponse
	(*ListBridgeResponse_Bridge)(nil),        // 13: satelit_datastore.ListBridgeResponse.Bridge
}
var file_satelitDatastore_proto_depIdxs = []int32{
	0,  // 0: satelit_datastore.GetDHCPLeaseResponse.lease:type_name -> satelit_datastore.DHCPLease
	13, // 1: satelit_datastore.ListBridgeResponse.bridges:type_name -> satelit_datastore.ListBridgeResponse.Bridge
	7,  // 2: satelit_datastore.NumaNode.pairs:type_name -> satelit_datastore.CorePair
	8,  // 3: satelit_datastore.RegisterTeleskopAgentRequest.nodes:type_name -> satelit_datastore.NumaNode
	7,  // 4: satelit_datastore.GetCPUCoreByPinningGroupResponse.pairs:type_name -> satelit_datastore.CorePair
	1,  // 5: satelit_datastore.SatelitDatastore.GetDHCPLease:input_type -> satelit_datastore.GetDHCPLeaseRequest
	3,  // 6: satelit_datastore.SatelitDatastore.GetHostnameByAddress:input_type -> satelit_datastore.GetHostnameByAddressRequest
	5,  // 7: satelit_datastore.SatelitDatastore.ListBridge:input_type -> satelit_datastore.ListBridgeRequest
	9,  // 8: satelit_datastore.SatelitDatastore.RegisterTeleskopAgent:input_type -> satelit_datastore.RegisterTeleskopAgentRequest
	11, // 9: satelit_datastore.SatelitDatastore.GetCPUCoreByPinningGroup:input_type -> satelit_datastore.GetCPUCoreByPinningGroupRequest
	2,  // 10: satelit_datastore.SatelitDatastore.GetDHCPLease:output_type -> satelit_datastore.GetDHCPLeaseResponse
	4,  // 11: satelit_datastore.SatelitDatastore.GetHostnameByAddress:output_type -> satelit_datastore.GetHostnameByAddressResponse
	6,  // 12: satelit_datastore.SatelitDatastore.ListBridge:output_type -> satelit_datastore.ListBridgeResponse
	10, // 13: satelit_datastore.SatelitDatastore.RegisterTeleskopAgent:output_type -> satelit_datastore.RegisterTeleskopAgentResponse
	12, // 14: satelit_datastore.SatelitDatastore.GetCPUCoreByPinningGroup:output_type -> satelit_datastore.GetCPUCoreByPinningGroupResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_satelitDatastore_proto_init() }
func file_satelitDatastore_proto_init() {
	if File_satelitDatastore_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_satelitDatastore_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DHCPLease); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satelitDatastore_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDHCPLeaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satelitDatastore_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDHCPLeaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satelitDatastore_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHostnameByAddressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satelitDatastore_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHostnameByAddressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satelitDatastore_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBridgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satelitDatastore_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBridgeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satelitDatastore_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CorePair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satelitDatastore_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumaNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satelitDatastore_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterTeleskopAgentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satelitDatastore_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterTeleskopAgentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satelitDatastore_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCPUCoreByPinningGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satelitDatastore_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCPUCoreByPinningGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satelitDatastore_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBridgeResponse_Bridge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_satelitDatastore_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_satelitDatastore_proto_msgTypes[8].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_satelitDatastore_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_satelitDatastore_proto_goTypes,
		DependencyIndexes: file_satelitDatastore_proto_depIdxs,
		MessageInfos:      file_satelitDatastore_proto_msgTypes,
	}.Build()
	File_satelitDatastore_proto = out.File
	file_satelitDatastore_proto_rawDesc = nil
	file_satelitDatastore_proto_goTypes = nil
	file_satelitDatastore_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SatelitDatastoreClient is the client API for SatelitDatastore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SatelitDatastoreClient interface {
	GetDHCPLease(ctx context.Context, in *GetDHCPLeaseRequest, opts ...grpc.CallOption) (*GetDHCPLeaseResponse, error)
	GetHostnameByAddress(ctx context.Context, in *GetHostnameByAddressRequest, opts ...grpc.CallOption) (*GetHostnameByAddressResponse, error)
	ListBridge(ctx context.Context, in *ListBridgeRequest, opts ...grpc.CallOption) (*ListBridgeResponse, error)
	RegisterTeleskopAgent(ctx context.Context, in *RegisterTeleskopAgentRequest, opts ...grpc.CallOption) (*RegisterTeleskopAgentResponse, error)
	GetCPUCoreByPinningGroup(ctx context.Context, in *GetCPUCoreByPinningGroupRequest, opts ...grpc.CallOption) (*GetCPUCoreByPinningGroupResponse, error)
}

type satelitDatastoreClient struct {
	cc grpc.ClientConnInterface
}

func NewSatelitDatastoreClient(cc grpc.ClientConnInterface) SatelitDatastoreClient {
	return &satelitDatastoreClient{cc}
}

func (c *satelitDatastoreClient) GetDHCPLease(ctx context.Context, in *GetDHCPLeaseRequest, opts ...grpc.CallOption) (*GetDHCPLeaseResponse, error) {
	out := new(GetDHCPLeaseResponse)
	err := c.cc.Invoke(ctx, "/satelit_datastore.SatelitDatastore/GetDHCPLease", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *satelitDatastoreClient) GetHostnameByAddress(ctx context.Context, in *GetHostnameByAddressRequest, opts ...grpc.CallOption) (*GetHostnameByAddressResponse, error) {
	out := new(GetHostnameByAddressResponse)
	err := c.cc.Invoke(ctx, "/satelit_datastore.SatelitDatastore/GetHostnameByAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *satelitDatastoreClient) ListBridge(ctx context.Context, in *ListBridgeRequest, opts ...grpc.CallOption) (*ListBridgeResponse, error) {
	out := new(ListBridgeResponse)
	err := c.cc.Invoke(ctx, "/satelit_datastore.SatelitDatastore/ListBridge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *satelitDatastoreClient) RegisterTeleskopAgent(ctx context.Context, in *RegisterTeleskopAgentRequest, opts ...grpc.CallOption) (*RegisterTeleskopAgentResponse, error) {
	out := new(RegisterTeleskopAgentResponse)
	err := c.cc.Invoke(ctx, "/satelit_datastore.SatelitDatastore/RegisterTeleskopAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *satelitDatastoreClient) GetCPUCoreByPinningGroup(ctx context.Context, in *GetCPUCoreByPinningGroupRequest, opts ...grpc.CallOption) (*GetCPUCoreByPinningGroupResponse, error) {
	out := new(GetCPUCoreByPinningGroupResponse)
	err := c.cc.Invoke(ctx, "/satelit_datastore.SatelitDatastore/GetCPUCoreByPinningGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SatelitDatastoreServer is the server API for SatelitDatastore service.
type SatelitDatastoreServer interface {
	GetDHCPLease(context.Context, *GetDHCPLeaseRequest) (*GetDHCPLeaseResponse, error)
	GetHostnameByAddress(context.Context, *GetHostnameByAddressRequest) (*GetHostnameByAddressResponse, error)
	ListBridge(context.Context, *ListBridgeRequest) (*ListBridgeResponse, error)
	RegisterTeleskopAgent(context.Context, *RegisterTeleskopAgentRequest) (*RegisterTeleskopAgentResponse, error)
	GetCPUCoreByPinningGroup(context.Context, *GetCPUCoreByPinningGroupRequest) (*GetCPUCoreByPinningGroupResponse, error)
}

// UnimplementedSatelitDatastoreServer can be embedded to have forward compatible implementations.
type UnimplementedSatelitDatastoreServer struct {
}

func (*UnimplementedSatelitDatastoreServer) GetDHCPLease(context.Context, *GetDHCPLeaseRequest) (*GetDHCPLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDHCPLease not implemented")
}
func (*UnimplementedSatelitDatastoreServer) GetHostnameByAddress(context.Context, *GetHostnameByAddressRequest) (*GetHostnameByAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHostnameByAddress not implemented")
}
func (*UnimplementedSatelitDatastoreServer) ListBridge(context.Context, *ListBridgeRequest) (*ListBridgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBridge not implemented")
}
func (*UnimplementedSatelitDatastoreServer) RegisterTeleskopAgent(context.Context, *RegisterTeleskopAgentRequest) (*RegisterTeleskopAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterTeleskopAgent not implemented")
}
func (*UnimplementedSatelitDatastoreServer) GetCPUCoreByPinningGroup(context.Context, *GetCPUCoreByPinningGroupRequest) (*GetCPUCoreByPinningGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCPUCoreByPinningGroup not implemented")
}

func RegisterSatelitDatastoreServer(s *grpc.Server, srv SatelitDatastoreServer) {
	s.RegisterService(&_SatelitDatastore_serviceDesc, srv)
}

func _SatelitDatastore_GetDHCPLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDHCPLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SatelitDatastoreServer).GetDHCPLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/satelit_datastore.SatelitDatastore/GetDHCPLease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SatelitDatastoreServer).GetDHCPLease(ctx, req.(*GetDHCPLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SatelitDatastore_GetHostnameByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostnameByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SatelitDatastoreServer).GetHostnameByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/satelit_datastore.SatelitDatastore/GetHostnameByAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SatelitDatastoreServer).GetHostnameByAddress(ctx, req.(*GetHostnameByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SatelitDatastore_ListBridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SatelitDatastoreServer).ListBridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/satelit_datastore.SatelitDatastore/ListBridge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SatelitDatastoreServer).ListBridge(ctx, req.(*ListBridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SatelitDatastore_RegisterTeleskopAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTeleskopAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SatelitDatastoreServer).RegisterTeleskopAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/satelit_datastore.SatelitDatastore/RegisterTeleskopAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SatelitDatastoreServer).RegisterTeleskopAgent(ctx, req.(*RegisterTeleskopAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SatelitDatastore_GetCPUCoreByPinningGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCPUCoreByPinningGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SatelitDatastoreServer).GetCPUCoreByPinningGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/satelit_datastore.SatelitDatastore/GetCPUCoreByPinningGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SatelitDatastoreServer).GetCPUCoreByPinningGroup(ctx, req.(*GetCPUCoreByPinningGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SatelitDatastore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "satelit_datastore.SatelitDatastore",
	HandlerType: (*SatelitDatastoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDHCPLease",
			Handler:    _SatelitDatastore_GetDHCPLease_Handler,
		},
		{
			MethodName: "GetHostnameByAddress",
			Handler:    _SatelitDatastore_GetHostnameByAddress_Handler,
		},
		{
			MethodName: "ListBridge",
			Handler:    _SatelitDatastore_ListBridge_Handler,
		},
		{
			MethodName: "RegisterTeleskopAgent",
			Handler:    _SatelitDatastore_RegisterTeleskopAgent_Handler,
		},
		{
			MethodName: "GetCPUCoreByPinningGroup",
			Handler:    _SatelitDatastore_GetCPUCoreByPinningGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "satelitDatastore.proto",
}
