version: '3'
services:
#  api:
#    build:
#      context: .
#    volumes:
#      - ./configs/satelit.yaml:/satelit.yaml
#    command:
#      - /go/src/github.com/whywaita/satelit/satelit
#      - -conf
#      - /satelit.yaml
#    environment:
#      GO111MODULE: "on"
#    ports:
#      - "9262:9262"
  proxy:
    build:
      context: ./examples/web/proxy
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
  client:
    command: /bin/sh -c "yarn && yarn start"
    stdin_open: true
    build:
      context: ./examples/web/webapp
      dockerfile: ./Dockerfile
    volumes:
      - ./examples/web/webapp:/client
      - /client/node_modules
    ports:
      - "3000:3000"
    environment:
      EXTEND_ESLINT: "true"