name: test
on:
  push:
    branches:
      - "**"
  pull_request: {}
jobs:
  test:
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - name: setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.x
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.GITHUB_TOKRN }}:x-oauth-basic@github.com/whywaita".insteadOf "https://github.com/whywaita"
      - name: lint
        run: |
          GO111MODULE=off GOBIN=$(pwd)/bin go get golang.org/x/lint/golint
          bin/golint -set_exit_status ./...
      - name: test
        run: |
          make test